#!/usr/bin/env python3
"""
Generate version information for firmware build
This script is automatically called by PlatformIO before compilation
"""

import os
import datetime
import subprocess

def get_git_hash():
    """Get current git commit hash"""
    try:
        return subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD']).decode('ascii').strip()
    except:
        return "unknown"

def get_git_branch():
    """Get current git branch"""
    try:
        return subprocess.check_output(['git', 'rev-parse', '--abbrev-ref', 'HEAD']).decode('ascii').strip()
    except:
        return "unknown"

def generate_version_header():
    """Generate version.h header file"""
    
    version_major = 1
    version_minor = 0
    version_patch = 0
    
    build_date = datetime.datetime.now().strftime("%Y-%m-%d")
    build_time = datetime.datetime.now().strftime("%H:%M:%S")
    build_timestamp = int(datetime.datetime.now().timestamp())
    
    git_hash = get_git_hash()
    git_branch = get_git_branch()
    
    header_content = f"""/**
 * @file version.h
 * @brief Auto-generated version information
 * 
 * This file is automatically generated by scripts/generate_version.py
 * DO NOT EDIT MANUALLY
 * 
 * Generated: {build_date} {build_time}
 */

#ifndef VERSION_H
#define VERSION_H

// Version numbers
#define VERSION_MAJOR       {version_major}
#define VERSION_MINOR       {version_minor}
#define VERSION_PATCH       {version_patch}

// Version string
#define VERSION_STRING      "{version_major}.{version_minor}.{version_patch}"

// Build information
#define BUILD_DATE          "{build_date}"
#define BUILD_TIME          "{build_time}"
#define BUILD_TIMESTAMP     {build_timestamp}

// Git information
#define GIT_HASH            "{git_hash}"
#define GIT_BRANCH          "{git_branch}"

// Full version string with git info
#define FULL_VERSION_STRING "{version_major}.{version_minor}.{version_patch}-{git_hash}"

#endif // VERSION_H
"""
    
    # Write to include/version.h
    version_file = os.path.join('include', 'version.h')
    
    # Create include directory if it doesn't exist
    os.makedirs('include', exist_ok=True)
    
    with open(version_file, 'w') as f:
        f.write(header_content)
    
    print(f"✓ Generated {version_file}")
    print(f"  Version: {version_major}.{version_minor}.{version_patch}")
    print(f"  Git: {git_hash} ({git_branch})")
    print(f"  Build: {build_date} {build_time}")

if __name__ == '__main__':
    generate_version_header()
